version: '3.8'

services:
  webclient:
    image: feedreader-webclient
    build:
      context: src/WebClient
      dockerfile: Dockerfile
    environment:
      - Blazor_Environment=local
    ports:
      - 5000:80

  webserver:
    image: feedreader-webserver
    build:
      context: src/WebServer
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DbConnectionString=Server=db;Port=5432;Database=feedreader;User Id=feedreader;Password=feedreader
      - FeedReaderJwtSecret=fake-feedreader-jwt-secret
    ports:
        - 5001:80

  taskserver:
    image: feedreader-taskserver
    build:
      context: src/TaskServer
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DbConnectionString=Server=db;Port=5432;Database=feedreader;User Id=feedreader;Password=feedreader

  db:
    image: postgres:14.1
    environment:
        - POSTGRES_DB=feedreader
        - POSTGRES_USER=feedreader
        - POSTGRES_PASSWORD=feedreader
        - PGDATA=/var/lib/postgresql/data/feedreaderdb
    volumes:
        - ${APPDATA}/feedreader/db:/var/lib/postgresql/data
    ports:
        - 5432:5432

  pgAdmin:
      image: dpage/pgadmin4:5.6
      environment:
          - PGADMIN_DEFAULT_EMAIL=test@test.com
          - PGADMIN_DEFAULT_PASSWORD=test
      ports:
          - 8080:80
      volumes:
          - ${APPDATA}/feedreader/pgadmin:/var/lib/pgadmin