version: '3.8'

services:
  db:
    image: postgres:13.4
    environment:
        - POSTGRES_DB=feedreader
        - POSTGRES_USER=feedreader
        - POSTGRES_PASSWORD=feedreader
        - PGDATA=/var/lib/postgresql/data/feedreaderdb
    volumes:
        - ${APPDATA}/feedreader/db:/var/lib/postgresql/data
    ports:
        - 5432:5432

  pgAdmin:
      image: dpage/pgadmin4:5.6
      environment:
          - PGADMIN_DEFAULT_EMAIL=test@test.com
          - PGADMIN_DEFAULT_PASSWORD=test
      ports:
          - 8080:80
      volumes:
          - ${APPDATA}/feedreader/pgadmin:/var/lib/pgadmin