apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedreader-webserver
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.webserver.replicas }}
  selector:
    matchLabels:
      app: feedreader-webserver
  template:
    metadata:
      labels:
        app: feedreader-webserver
    spec:
      containers:
      - name: feedreader-webserver
        image: {{ .Values.webserver.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: ConnectionStrings__DbConnectionString
            valueFrom:
              secretKeyRef:
                name: feedreader-db-secret
                key: db-conn
          - name: FeedReaderJwtSecret
            valueFrom:
              secretKeyRef:
                name: feedreader-jwt-secret
                key: key
          - name: StaticServer
            value: {{ .Values.webserver.address }}
---
apiVersion: v1
kind: Service
metadata:
  name: feedreader-webserver
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: feedreader-webserver
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feedreader-webserver
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.webserver.domain }}
    secretName: feedreader-webserver-tls
  rules:
  - host: {{ .Values.webserver.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: feedreader-webserver
            port:
              number: 8080