apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedreader-taskserver
  namespace: feedreader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedreader-taskserver
  template:
    metadata:
      labels:
        app: feedreader-taskserver
    spec:
      containers:
      - name: feedreader-taskserver
        image:  xieyubo/feedreader-taskserver
        imagePullPolicy: Always
        env:
          - name: ConnectionStrings__DbConnectionString
            valueFrom:
              secretKeyRef:
                name: feedreader-taskserver-secret
                key: db-conn
      nodeSelector:
        kubernetes.io/arch: arm64
