apiVersion: apps/v1
kind: Deployment
metadata:
  name: frtasksrv
  namespace: yuboxie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frtasksrv
  template:
    metadata:
      labels:
        app: frtasksrv
    spec:
      containers:
      - name: frtasksrv
        image:  xieyubo/frtasksrv
        imagePullPolicy: Always
        env:
          - name: ConnectionStrings__DbConnectionString
            valueFrom:
              secretKeyRef:
                name: frdbsec
                key: db-conns
      nodeSelector:
        kubernetes.io/arch: arm64
