apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: feedreader-release-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      imagePullSecrets:
      - name: xyb-private-docker-registry
      containers:
      - name: webserver
        image: docker.xyb.name/feedreader-release-a/webserver:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: ConnectionStrings__DbConnectionString
            valueFrom:
              secretKeyRef:
                name: feedreader-release-db-secret
                key: db-conns
          - name: FeedReaderJwtSecret
            valueFrom:
              secretKeyRef:
                name: feedreader-release-jwt-secret
                key: key
          - name: StaticServer
            value: https://cdn.release-a.feedreader.org
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: feedreader-release-a
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: webserver
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webserver
  namespace: feedreader-release-a
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - api.release-a.feedreader.org
    secretName: webserver-https-secret
  rules:
  - host: api.release-a.feedreader.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webserver
            port:
              number: 80