name: Main CI

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Container Repository
        uses: docker/login-action@v1
        with:
          username: feedreaderorg2
          password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}

      - name: Build And Push Docker Image for webclient
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64
          file: src/WebClient/Dockerfile
          tags: feedreaderorg2/feedreader-webclient:latest,feedreaderorg2/feedreader-webclient:${{ github.sha }}
          push: true

      - name: Build And Push Docker Image for webserver
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64
          file: src/WebServer/Dockerfile
          tags: feedreaderorg2/feedreader-webserver:latest,feedreaderorg2/feedreader-webserver:${{ github.sha }}
          push: true

      - uses: azure/k8s-set-context@v1
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'

      - name: Deploy WebServer
        run: |
          helm upgrade --install feedreader helm/ --namespace feedreader-main --create-namespace \
            --set webclient.blazor_environment=main \
            --set webclient.domain=www.main.feedreader.org \
            --set webclient.image=feedreaderorg2/feedreader-webclient:${{ github.sha }} \
            --set webclient.replicas=1 \
            --set webserver.address=https://api.main.feedreader.org \
            --set webserver.domain=api.main.feedreader.org \
            --set webserver.image=feedreaderorg2/feedreader-webserver:${{ github.sha }} \
            --set webserver.replicas=1