name: Master CI

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup DotNet Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build

      - name: Publish
        run: dotnet publish -c Release --no-build

      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Login Container Repository
        uses: docker/login-action@v1
        with:
          registry: docker.xyb.name
          username: ${{ secrets.DOCKER_REPOSITORY_USERNAME }}
          password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}

      - name: Build And Push Docker Image for webclient
        uses: docker/build-push-action@v2
        with:
          context: src/WebClient/
          file: src/WebClient/Dockerfile
          tags: docker.xyb.name/feedreader-devtest/webclient:latest,docker.xyb.name/feedreader-devtest/webclient:master-${{ github.sha }}
          push: true

      - name: Build And Push Docker Image for webserver
        uses: docker/build-push-action@v2
        with:
          context: src/WebServer/
          file: src/WebServer/Dockerfile
          tags: docker.xyb.name/feedreader-devtest/webserver:latest,docker.xyb.name/feedreader-devtest/webserver:master-${{ github.sha }}
          push: true

      - name: Build And Push Docker Image for taskserver
        uses: docker/build-push-action@v2
        with:
          context: src/TaskServer/
          file: src/TaskServer/Dockerfile
          tags: docker.xyb.name/feedreader-devtest/taskserver:latest,docker.xyb.name/feedreader-devtest/taskserver:master-${{ github.sha }}
          push: true

      - name: Build And Push Docker Image for messageserver
        uses: docker/build-push-action@v2
        with:
          context: .
          file: src/MessageServer/Dockerfile
          tags: docker.xyb.name/feedreader-devtest/messageserver:master-${{ github.sha }}
          push: true

      - name: Build And Push Docker Image for textclassificationserver
        uses: docker/build-push-action@v2
        with:
          context: src/TextClassificationServer
          file: src/TextClassificationServer/Dockerfile
          tags: docker.xyb.name/feedreader-devtest/textclassificationserver:master-${{ github.sha }}
          push: true

      - uses: azure/k8s-set-context@v1
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'

      - name: Deploy To Azure Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          namespace: feedreader-devtest
          manifests: |
            kubernetes/devtest-configs/webclient.yaml
            kubernetes/devtest-configs/webserver.yaml
            kubernetes/devtest.yaml
          images: |
            docker.xyb.name/feedreader-devtest/webclient:master-${{ github.sha }}
            docker.xyb.name/feedreader-devtest/webserver:master-${{ github.sha }}
            docker.xyb.name/feedreader-devtest/messageserver:master-${{ github.sha }}