name: Release-B CI

on:
  push:
    branches:
      - release-b

env:
  DOTNET_VERSION: '7.0'
  TARGET_BRANCH: 'release-b'

jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup DotNet Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build

      - name: Publish
        run: |
          dotnet publish -c Release --no-build
          mv src/WebClient/bin/Release/net${{ env.DOTNET_VERSION }}/publish/wwwroot/staticwebapp.${{ env.TARGET_BRANCH }}.config.json src/WebClient/bin/Release/net${{ env.DOTNET_VERSION }}/publish/wwwroot/staticwebapp.config.json

      - name: Login Container Repository
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REPOSITORY_USERNAME }}
          password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}

      - name: Build And Push Docker Image for webclient
        uses: docker/build-push-action@v2
        with:
          context: src/WebClient/
          file: src/WebClient/Dockerfile
          tags: xieyubo/feedreader-webclient:${{ github.sha }}
          push: true

      - name: Build And Push Docker Image for webserver
        uses: docker/build-push-action@v2
        with:
          context: .
          file: src/WebServer/Dockerfile
          tags: xieyubo/feedreader-webserver:${{ github.sha }}
          push: true

      - name: Build And Push Docker Image for taskserver
        uses: docker/build-push-action@v2
        with:
          context: src/TaskServer/
          file: src/TaskServer/Dockerfile
          tags: xieyubo/feedreader-taskserver:${{ github.sha }}
          push: true

      - uses: azure/k8s-set-context@v1
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'

      - name: Deploy WebServer
        uses: azure/k8s-deploy@v1
        with:
          namespace: feedreader
          manifests: |
            kubernetes/${{ env.TARGET_BRANCH }}-configs/webserver.yaml
          images: |
            xieyubo/feedreader-webserver-${{ github.sha }}

      - name: Deploy TaskServer
        uses: azure/k8s-deploy@v1
        with:
          namespace: feedreader
          manifests: |
            kubernetes/${{ env.TARGET_BRANCH }}-configs/taskserver.yaml
          images: |
            xieyubo/feedreader-taskserver:${{ github.sha }}

      # - name: Deploy WebClient
      #   uses: Azure/static-web-apps-deploy@v1
      #   with:
      #     azure_static_web_apps_api_token: ${{ secrets.WEBCLIEN_RELEASE_B_DEPLOY_TOKEN }}
      #     action: "upload"
      #     skip_app_build: true
      #     skip_api_build: true
      #     app_location: "src/WebClient/bin/Release/net${{ env.DOTNET_VERSION }}/publish/wwwroot"
      #     api_location: ""