name: Master CI

on:
  push:
    branches:
      - release/a

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup DotNet Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build

      - name: Publish
        run: dotnet publish -c Release --no-build

      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Login Container Repository
        uses: docker/login-action@v1
        with:
          registry: docker.xyb.name
          username: ${{ secrets.DOCKER_REPOSITORY_USERNAME }}
          password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}

      - name: Build And Push Docker Image for webclient
        uses: docker/build-push-action@v2
        with:
          context: src/WebClient/
          file: src/WebClient/Dockerfile
          tags: docker.xyb.name/feedreader-release-a/webclient:latest,docker.xyb.name/feedreader-release-a/webclient:release-a-${{ github.sha }}
          push: true

      - name: Build And Push Docker Image for webserver
        uses: docker/build-push-action@v2
        with:
          context: src/WebServer/
          file: src/WebServer/Dockerfile
          tags: docker.xyb.name/feedreader-release-a/webserver:latest,docker.xyb.name/feedreader-release-a/webserver:release-a-${{ github.sha }}
          push: true

      - name: Build And Push Docker Image for taskserver
        uses: docker/build-push-action@v2
        with:
          context: src/TaskServer/
          file: src/TaskServer/Dockerfile
          tags: docker.xyb.name/feedreader-release-a/taskserver:latest,docker.xyb.name/feedreader-release-a/taskserver:release-a-${{ github.sha }}
          push: true

      - uses: azure/k8s-set-context@v1
        with:
          kubeconfig: '${{ secrets.KUBECONFIG }}'

      - name: Deploy To Azure Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          namespace: feedreader-release-a
          manifests: |
            kubernetes/release-a-configs/webclient.yaml
            kubernetes/release-a-configs/webserver.yaml
          images: |
            docker.xyb.name/feedreader-release-a/webclient:release-a-${{ github.sha }}
            docker.xyb.name/feedreader-release-a/webserver:release-a-${{ github.sha }}